updated scripts

diff --git a/i3-auto-float b/i3-auto-float
--- a/i3-auto-float
+++ b/i3-auto-float
@@ -2,29 +2,67 @@
 
 # Author:       Action <dev@action-server.com>
 # License:      GNU GPLv3
-# Description:  Add or remove floating flag
+# Description:  Enable or disable floating for specified windows
 
-# ENV
-WORKDIR="$XDG_CONFIG_HOME"/i3
-NAME="$(basename $0)"
-mkdir -p "$WORKDIR"/configs
-touch "$WORKDIR"/configs/float.config
+# Env
+set -e
+script_name="$(basename "$0")"
+script_ver='v0.1'
 
-if ! which i3-modular-config >/dev/null 2>&1; then
-	echo "$NAME - Error: Dependency not found: \"i3-modular-config\"."
-	exit 1
-fi
+print_error(){
+	message="$1"
+	echo "${script_name} - Error: ${message}" >&2
+	notify-send "${script_name}" "Error: ${message}"
+}
 
-# Run
-current_window_class="$(xprop -id $(xdotool getactivewindow) | grep '^WM_CLASS(STRING)' | sed -n 's/^WM_CLASS.*"\(.*\)"$/\1/p')"
-current_window_name="$(xprop -id $(xdotool getactivewindow) | grep '^WM_NAME(STRING)' | sed -n 's/^WM_NAME.*"\(.*\)"$/\1/p')"
-[ -n "$current_window_class" ] && current_window_class="class=\"$current_window_class\""
-[ -n "$current_window_name" ] && current_window_name="title=\"$current_window_name\""
-if ! grep -q -i "${current_window_class}.*${current_window_name}" "$WORKDIR"/configs/float.config; then
-	printf "for_window [$current_window_class $current_window_name] floating enable\n" >> "$WORKDIR"/configs/float.config
-else
-	sed -i.bak '/^.*'"$current_window_class"'.*'"$current_window_name"'.*$/d' "$WORKDIR"/configs/float.config
-fi
+setup(){
+	workdir="$XDG_CONFIG_HOME"/i3
 
-i3-modular-config && i3-msg 'reload' && notify-send 'i3' 'Reloaded config'
-i3-msg 'floating toggle'
+	# Check XDG standard
+	if [ -z "$XDG_CONFIG_HOME" ]; then
+		workdir="$HOME"/.i3
+	fi
+
+	# Check i3-modular-config is installed
+	if ! command -v i3-modular-config >/dev/null 2>&1; then
+		print_error 'i3-modular-config missing.'
+		exit 1
+	fi
+
+	mkdir -p "$workdir"/configs
+	touch "$workdir"/configs/float.config
+}
+
+run(){
+	# Get window class and name
+	current_window_class="$(xprop WM_CLASS -id "$(xdotool getactivewindow)" | sed -n 's/^WM_CLASS.*"\(.*\)"$/\1/p')"
+	current_window_name="$(xprop WM_NAME -id "$(xdotool getactivewindow)" | sed -n 's/^WM_NAME.*"\(.*\)"$/\1/p')"
+
+	# Check window class or name is empty
+	if [ -z "$current_window_class" ] || [ -z "$current_window_name" ]; then
+		print_error 'Window class or name not found.'
+		i3-msg 'floating toggle'
+		exit 1
+	fi
+
+	current_window_class="class=\"$current_window_class\""
+	current_window_name="title=\"$current_window_name\""
+
+	# Toggle float
+	if ! grep -q -i "${current_window_class}.*${current_window_name}" "$workdir"/configs/float.config; then
+		printf '%s\n' "for_window [$current_window_class $current_window_name] floating enable" >> "$workdir"/configs/float.config
+	else
+		sed -i.bak '/^.*'"$current_window_class"'.*'"$current_window_name"'.*$/d' "$workdir"/configs/float.config
+	fi
+
+	# Reload i3 and notify user
+	i3-modular-config && i3-msg 'reload'
+	i3-msg 'floating toggle'
+}
+
+main(){
+	setup
+	run
+}
+
+main "$@"
diff --git a/i3-modular-config b/i3-modular-config
--- a/i3-modular-config
+++ b/i3-modular-config
@@ -4,40 +4,61 @@
 # License:      GNU GPLv3
 # Description:  Modular i3 config support
 
-# ENV
-NAME="$(basename $0)"
-WORKDIR="$XDG_CONFIG_HOME"/i3
+# Env
+set -e
+script_name="$(basename $0)"
+script_ver='v0.1'
 
-prepare(){
-	#Create necessary files and directories
-	mkdir -p "$WORKDIR"/configs
-	mkdir -p "$WORKDIR"/data
-	touch "$WORKDIR"/data/list
-	[ -f "$WORKDIR"/config.bak ] || cp "$WORKDIR"/config "$WORKDIR"/config.bak
+print_error(){
+	message="$1"
+	echo "${script_name} - Error: ${message}" >&2
+	notify-send "${script_name}" "Error: ${message}"
+}
+
+setup(){
+	workdir="$XDG_CONFIG_HOME"/i3
+
+	# Check XDG standard
+	if [ -z "$XDG_CONFIG_HOME" ]; then
+		workdir="$HOME"/.i3
+	fi
+
+	# Create necessary files and directories
+	mkdir -p "$workdir"/configs
+	mkdir -p "$workdir"/data
+	touch "$workdir"/data/list
+
+	# Create backup config
+	if ! [ -f "$workdir"/config.bak ] && [ -f "$workdir"/config ]; then
+		cp "$workdir"/config "$workdir"/config.bak
+	fi
 }
 
 run(){
 	# Clear i3 config file
-	cat /dev/null > "$WORKDIR"/config
+	cat /dev/null > "$workdir"/config
 
-	# Looping through files in the list and concatenating the output
+	# Looping through files in the list and Appending the output to config
 	while read x; do
 		# Ignore comments
-		if printf "$x" | grep -q '^\s*#.*$'; then
+		if printf '%s' "$x" | grep -q '^\s*#.*$'; then
 			continue
-		elif [ -f "$WORKDIR"/configs/"$x" ]; then
-			cat "$WORKDIR"/configs/"$x" >> "$WORKDIR"/config
-		else
-			echo "$NAME - Error: $WORKDIR/configs/$x not found." >&2
+		fi
+
+		# Check file found
+		if ! [ -f "$workdir"/configs/"$x" ]; then
+			print_error "${workdir}/configs/${x} not found."
 			exit 1
 		fi
-	done < "$WORKDIR"/data/list
+
+		# Append content to config
+		cat "$workdir"/configs/"$x" >> "$workdir"/config
+	done < "$workdir"/data/list
 }
 
 main(){
-	prepare
+	setup
 	run
-	printf "$NAME: Done."
 }
 
-main
+main "$@"
